### ISSUE TITLE
Add example scripts to wiki

### ISSUE THREAD

**Issue by WrongWeekend** [AustereTony-MCMods/Plant-Biomes#1]
It's not totally clear how the scripts for whitelisting or blacklisting are supposed to be formatted. Apparently there's supposed to be a user guide, but the "Overall Settings" link simply goes back to the wiki home.

**Comment by AustereTony-MCMods** [comment]
Something went wrong with sidebar. You could navigate to "Overall Settings" directly from pages list and also i added links to main page.

**Comment by AustereTony-MCMods** [comment]
Consider it closed.
