### ISSUE TITLE
Manual plants_settings.json config scripting issues

### ISSUE THREAD

**Issue by WrongWeekend** [AustereTony-MCMods/Plant-Biomes#2]
A couple things I've run into while working with this mod (using version 1.3.12). I suspect that they are related to one another:

1. Settings do not seem to carry over between worlds or gameplay sessions, despite the game settings seemingly using the same file (plants_settings.json). If I use /pb commands to disable growth of a plant in a certain biome, and the settings are saved, they will not apply if I start a new world. /pb settings does not seem to register any settings and bonemeal has normal effects.

2. Copy/pasting lists of blacklisted biomes between plants directly in the config does not work either, as /pb settings does not register any of the script. Neither does copy/pasting data for different block states of the same plant.

**Comment by AustereTony-MCMods** [comment]
Hello. About your questions:
1. All settings loaded when you start server or load singleplayer world. I tested it and it is loading and reloading as supposed to. Is there are some data in file and "/pb settings" shows nothing? If so i suppose "plants_data.json" structure is damaged by manual changes and config can't be parsed properly. I suggest you to remove "config.json" and "plants_settings.json" and try to customize plants with commands only - it should work. If existing commands aren't flexible enough, you can suggest new commands. 
2. See first answer. Also settings loaded only once, so any manual changes will not be applied until world reload. I will add command for forced reloading, but manual editing still not recommended.

Anyway you can show me your settings file and i will inspect it. I will add new section to wiki with settings file structure description.

**Comment by WrongWeekend** [comment]
I'll admit it was an error in my syntax that prevented the settings from registering.

Although I would like to bring up an additional issue:

https://i.imgur.com/y9CbKva.png
Using the script linked below, attempting to bonemeal wheat, potatoes, carrots, and beetroots in creative mode shows the smoke particles, indicating a denied biome, but also still gives the green sparkles and boosts the crop growth anyway. This does not happen with pumpkins, melons, or Immersive Engineering hemp- those plants show the smoke particles with no growth as intended.

Here is my script: https://pastebin.com/K6S1JFRN

I also think being able to apply a single list of settings to all blockstates of a certain plant would be helpful.

**Comment by AustereTony-MCMods** [comment]
Sorry for late answer. 
Does it happen only in creative mode? I couldnt get such effect, everything works properly. Please, leave your mod list, may be some mod causes it.

> I also think being able to apply a single list of settings to all blockstates of a certain plant would be helpful.

There are already such feature. You can type "/pb set-main" to apply latest subtype settings to whole plant. See more info at wiki.

I recently released 1.4.0 version, some proplems might be solved. Also command for settings reloading was added ("/pb reload"), manual settings management should be easier.

**Comment by WrongWeekend** [comment]
Found the problem; Hunger Overhaul's bonemeal configs seem to conflict with Plant Biomes. Turning off HO's bonemeal configs solves the issue.

**Comment by AustereTony-MCMods** [comment]
Thank you for investigation. As i can see in Hunger Overhaul's sources it modifies bonemeal behavior with Forge event, so it ignore many things and also Plant Biomes settings. Here is the problem: [link](https://github.com/progwml6/HungerOverhaul/blob/c9424c36c81053904e611a779348f7138f44600e/src/main/java/iguanaman/hungeroverhaul/module/bonemeal/BonemealModule.java#L63). I will fix it in further patches. You can open appropriate issue if you want.

**Comment by AustereTony-MCMods** [comment]
Should be fixed in 1.4.6.

**Comment by AustereTony-MCMods** [comment]
If there are no questions, i consider issue closed.
