### ISSUE TITLE
Dynamic Trees Saplings still not supported

### ISSUE THREAD

**Issue by WrongWeekend** [AustereTony-MCMods/Plant-Biomes#4]
First off I just wanted to say that I appreciate your quick response to these issues and frequent updates.

I tried out adding the dynamic trees saplings (just the 8 basic ones, including cactus) but was met with a "This plant is unsupported" error for each. Trying to add the planted seed (represented in-world by a 3d sapling model) as well both as the branches and leaves of each plant were all unsuccessful. This is despite the 1.4.6 update indicating that the mod supports Dynamic Trees saplings.

**Comment by AustereTony-MCMods** [comment]
My bad. It works for 1.4.6 if any other mod, that adds special plants (with tiles) also loaded (IC2, Forestry, Agricraft) - some checks were broken. Fixed it in 1.4.8.

**Comment by AustereTony-MCMods** [comment]
If there are no questions, i consider issue closed.
